repos:
  # Hooks Git de base (pour tout)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  # Python backend (FastAPI/SQLAlchemy)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8  # Dernière stable
    hooks:
      - id: ruff  # Lint + fix auto
        args: [--fix]
      - id: ruff-format  # Black-like formatter

  # Sécurité Python (bandit pour SQLi, detect-secrets pour API_KEY)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
       - id: bandit
         name: bandit
         entry: bandit
         language: python
         types: [python]
         args: ["-r"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/bridgecrewio/checkov
    rev: '3.2.0'
    hooks:
      - id: checkov
        args: ["--framework", "dockerfile,docker_compose", "--quiet"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: ["--ignore", "DL3008"]
