# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks
        env:
          SKIP: hadolint
        run: pre-commit run --all-files

  sonar:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  hadolint:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile

  checkov:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile
          soft_fail: false

  build-and-scan:
    needs: [hadolint, checkov]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        run: docker build -t backend:test ./backend

      - name: Trivy backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:test
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Build frontend
        run: docker build -t frontend:test ./frontend

      - name: Trivy frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:test
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

  push:
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push backend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build & Push frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository }}/frontend:latest
